apiVersion: v1
kind: Namespace
metadata:
  name: msignite
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: legacywindows
spec:
  ports:
    -
      name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: legacywindows
  labels:
      app: modernapp
      version: v1
subsets:
- addresses:
  - ip: 23.100.1.189
  ports:
  - name: http
    port: 80
    protocol: TCP