apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: modernapp-gw
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: modernapp
spec:
  hosts:
  - "*"
  gateways:
  - modernapp-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: legacywindows.msignite.svc.cluster.local
        port:
          number: 80