apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: modernapp
spec:
  hosts:
  - "*"
  gateways:
  - modernapp-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: modernapp-lb.msignite.svc.cluster.local
        port:
          number: 80
      weight: 100